### ISSUE TITLE
[BUG] Legacy loot table referenced

### ISSUE THREAD

**Issue by benjathje** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#122]
**Describe the bug**
The loot table for this container [ctov:village/taiga/archer] resolved to empty and loot could not be generated. Check your `latest.log` for errors.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open chest
2. Error message appears

**Expected behaviour**
Items appear

**Screenshots**
![image](https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village/assets/26327698/c43d3ad8-feee-455a-b671-cdec61016aea)

**Minecraft Version**
1.20.1

**CTOV Version**
3.3.6

**Add-ons used**

**Log**
https://mclo.gs/c15XCQl

**Additional context**
Prominence II modpack

**Comment by ChoiceTheorem** [comment]
Fixed in CTOV 3.4.3

**Comment by mxKeaton** [comment]
[latest.log](https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village/files/15031467/latest.log)

The issue still occures on Version 3.4.3. Just went through a savanna village and over halve of the chests resulted in the error.

I am also running Lootr, maybe it is connected to the issue.
